# Generated by Django 4.2.3 on 2023-07-31 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_user_author_authoruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authorRating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentRating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='articleRating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='categoryThrough',
            new_name='categoryTr',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='postThrough',
            new_name='postTr',
        ),
    ]
