# Generated by Django 4.2.5 on 2023-10-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_authorrating_author_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='sdffssfsfsfsfsfsfsfsfsfsfsfsf'),
            preserve_default=False,
        ),
    ]
